# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in d_primitive_data_types.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rake-compiler"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"
